In [27]:
import pandas as pd
import numpy as np
import seaborn as sns
import sklearn as skl
import matplotlib.pyplot as plt
import matplotlib.figure as ff

# importar librerias de preprocesamiento
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.metrics.pairwise import euclidean_distances

from sklearn import metrics

In [28]:
#TRAEMOS EL ARCHIVO EXCEL A UN DATAFRAME DE PANDAS
df = pd.read_excel("Tabla_GDP_1parcial.xlsx")
df

,province,gdp,illiteracy,poverty,deficient_infra,school_dropout,no_healthcare,birth_mortal,pop,movie_theatres_per_cap,doctors_per_cap
0,Buenos Aires,2.926899e+08,1.383240,8.167798,5.511856,0.766168,48.7947,4.4,15625084,0.000006,0.004836
1,Catamarca,6.150949e+06,2.344140,9.234095,10.464484,0.951963,45.0456,1.5,367828,0.000005,0.004502
2,Córdoba,6.936374e+07,2.714140,5.382380,10.436086,1.035056,45.7640,4.8,3308876,0.000011,0.010175
3,Corrientes,7.968013e+06,NaN,12.747191,17.438858,3.864265,62.1103,5.9,992595,0.000004,0.004495
4,Chaco,9.832643e+06,7.517580,15.862619,31.479527,2.577462,65.5104,7.5,1055259,0.000003,0.003605
5,Chubut,1.774785e+07,1.548060,8.051752,8.044618,0.586309,39.5473,3.0,509108,0.000016,0.004498
6,Entre Ríos,2.074341e+07,3.185580,7.288751,18.794568,NaN,NaN,3.1,1235994,0.000006,0.004679
7,Formosa,3.807057e+06,4.610640,17.035583,28.004985,2.268974,65.8126,16.2,530162,0.000004,0.003440
8,Jujuy,NaN,2.151390,13.367965,12.483179,0.721295,54.1615,3.7,673307,0.000003,0.003958
9,La Pampa,6.990262e+06,1.539300,3.398774,16.505714,0.204093,45.4764,7.2,318951,0.000019,0.005415
10,La Rioja,5.590516e+06,2.773210,10.875152,7.403254,3.844949,40.8341,11.4,333642,0.000012,0.005092
11,Mendoza,3.343137e+07,2.200200,5.692798,3.839852,NaN,50.5843,4.4,1738929,0.000008,0.005720
12,Misiones,9.646826e+06,6.863950,13.529788,8.325740,3.129124,57.8339,8.1,1101593,0.000002,0.002880
13,Neuquén,2.256411e+07,1.943750,9.456635,11.267278,1.393504,48.7431,3.3,551266,0.000009,0.005067
14,Río Negro,NaN,NaN,8.678391,14.885444,0.408042,49.9463,0.8,638645,0.000009,0.004898
15,Salta,1.343883e+07,3.346090,16.870500,14.182303,1.482030,NaN,5.8,1214441,0.000004,0.003991
16,San Juan,8.262309e+06,2.963260,9.050784,3.914390,3.298413,52.9684,4.2,681055,0.000006,0.005044
17,San Luis,1.178085e+07,3.433650,6.593771,9.679894,2.000172,51.6154,3.8,432310,0.000005,0.006102
18,Santa Cruz,1.166374e+07,0.791485,8.024762,7.411364,0.289262,29.2321,3.3,273964,0.000011,0.004271
19,Santa Fe,8.158869e+07,1.975940,6.081012,11.869195,2.872181,41.9660,2.6,3194537,0.000007,0.006672
20,Santiago del Estero,8.387859e+06,6.272090,11.759000,20.491433,2.325598,63.6637,1.7,874006,0.000003,0.002821
21,Tucumán,1.385620e+07,3.770370,11.214239,6.466665,0.977285,48.2242,3.0,1448188,0.000005,0.005501

In [29]:
#ANALIZAMOS VALORES NULOS
df.isnull().sum()

province                  0
gdp                       2
illiteracy                2
poverty                   0
deficient_infra           0
school_dropout            2
no_healthcare             2
birth_mortal              0
pop                       0
movie_theatres_per_cap    0
doctors_per_cap           0
dtype: int64

MANEJO DE VALORES NULOS, ELECCIÓN ENTRE LA MEDIA Y LA MEDIANA

In [30]:
school_media = df["school_dropout"].mean()
school_mediana = df["school_dropout"].median()
print(f"La media es: {round(school_media, 2)} y la mediana: {round(school_mediana, 2)}")

La media es: 1.75 y la mediana: 1.44

In [31]:
illiteracy_media = df["illiteracy"].mean()
illiteracy_mediana = df["illiteracy"].median()
print(f"La media es: {round(illiteracy_media, 2)} y la mediana: {round(illiteracy_mediana, 2)}")

La media es: 3.17 y la mediana: 2.74

In [32]:
#MANEJO DE VALORES NULOS: IMPUTACIÓN POR LA MEDIANA, CONSIDERAMOS QUE ES LA MEJOR MEDIDA DE TENDENCIA CENTRAL EN ESTE CASO
school_mediana = df["school_dropout"].median()
illiteracy_mediana = df["illiteracy"].median()

df["school_dropout"].fillna(school_mediana, inplace= True)
df["illiteracy"].fillna(illiteracy_mediana, inplace= True)

C:\Users\kemer\AppData\Local\Temp\ipykernel_6848\1160651256.py:5: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.



C:\Users\kemer\AppData\Local\Temp\ipykernel_6848\1160651256.py:6: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.

In [33]:
#ESTANDARIZAMOS LAS VARIABLES
scaler = StandardScaler()
df[["z_school_dropout", "z_illiteracy", "z_doctors_per_cap"]] = scaler.fit_transform(df[["school_dropout", "illiteracy", "doctors_per_cap"]])

In [34]:
#DEFINICIÓN DE VARIABLES PARA NUESTRO CLÚSTER
X_clustering = pd.DataFrame(df, columns = ["z_school_dropout", "z_illiteracy", "z_doctors_per_cap"], dtype=float)
X_clustering

    z_school_dropout  z_illiteracy  z_doctors_per_cap
0          -0.853003     -1.013730          -0.039069
1          -0.687099     -0.455425          -0.263350
2          -0.612902     -0.240447           3.551749
3           1.913420     -0.223286          -0.267934
4           0.764379      2.550462          -0.866760
5          -1.013607     -0.917966          -0.266068
6          -0.253304      0.033471          -0.144510
7           0.488917      0.861463          -0.977277
8          -0.893073     -0.567417          -0.629194
9          -1.354904     -0.923056           0.350293
10          1.896172     -0.206126           0.133529
11         -0.253304     -0.539058           0.555776
12          1.256982      2.170688          -1.353917
13         -0.292828     -0.688061           0.116203
14         -1.172789     -0.223286           0.002791
15         -0.213779      0.126731          -0.606961
16          1.408146     -0.095702           0.100821
17          0.248892      0.177605           0.812602
18         -1.278853     -1.357553          -0.419007
19          1.027546     -0.669358           1.195642
20          0.539479      1.826804          -1.393514
21         -0.664488      0.373247           0.408154

In [35]:
#CALCULAMOS LAS DISTANCIAS EUCLIDEAS NUEVAMENTE
distances = euclidean_distances(X_clustering)
distances

array([[0.        , 0.62412376, 3.68097679, 2.88622199, 4.00055716,
        0.29409624, 1.21135719, 2.48944383, 0.74097744, 0.64166141,
        2.8705364 , 0.96891338, 4.03997214, 0.66630734, 0.85370772,
        1.42539767, 2.44441009, 1.83270191, 0.66626965, 2.27586589,
        3.44124342, 1.4694394 ],
       [0.62412376, 0.        , 3.82187154, 2.61086353, 3.39208576,
        0.56617892, 0.66431931, 1.90444163, 0.43452148, 1.02039206,
        2.62544334, 0.9306661 , 3.4445976 , 0.59466725, 0.60051186,
        0.82523032, 2.15686663, 1.56028205, 1.09006272, 2.26151045,
        2.82671717, 1.06683046],
       [3.68097679, 3.82187154, 0.        , 4.5795825 , 5.40456198,
        3.89811744, 3.72379838, 4.78960138, 4.20305681, 3.35646224,
        4.2403842 , 3.03221631, 5.77716087, 3.47933654, 3.59289206,
        4.19392258, 4.00181121, 2.90178907, 4.1783156 , 2.90280443,
        5.48243819, 3.20335262],
       [2.88622199, 2.61086353, 4.5795825 , 0.        , 3.06146465,
        3.0083332 , 2.1853719 , 1.92589154, 2.85049756, 3.39909146,
        0.40219973, 2.33942345, 2.70949824, 2.28716169, 3.09806061,
        2.18229906, 0.63840368, 2.02458061, 3.39116359, 1.76799544,
        2.71247363, 2.73103609],
       [4.00055716, 3.39208576, 5.40456198, 3.06146465, 0.        ,
        3.94360902, 2.80937101, 1.71487886, 3.53903263, 4.24710469,
        3.14329577, 3.55026953, 0.79006816, 3.54569181, 3.49319543,
        2.6265492 , 2.89012675, 2.95236046, 4.43259035, 3.83275277,
        0.92289279, 2.89953955],
       [0.29409624, 0.56617892, 3.89811744, 3.0083332 , 3.94360902,
        0.        , 1.22395583, 2.43511016, 0.51891544, 0.70456407,
        3.02211956, 1.18197201, 3.98481703, 0.84764872, 0.76171099,
        1.35916245, 2.58372057, 1.98939873, 0.53570799, 2.52283605,
        3.34917415, 1.49789511],
       [1.21135719, 0.66431931, 3.72379838, 2.1853719 , 2.80937101,
        1.22395583, 0.        , 1.38923079, 1.00264071, 1.54055037,
        2.18058704, 0.90453801, 2.88293636, 0.76820661, 0.96595801,
        0.47341338, 1.68442573, 1.09043124, 1.7498704 , 1.98256158,
        2.32477018, 0.7680877 ],
       [2.48944383, 1.90444163, 4.78960138, 1.92589154, 1.71487886,
        2.43511016, 1.38923079, 0.        , 2.01810684, 2.88905213,
        2.08662491, 2.20513   , 1.56392154, 2.0513037 , 2.21325071,
        1.08201067, 1.70980785, 1.93104646, 2.89148862, 2.71203015,
        1.05246953, 1.86764988],
       [0.74097744, 0.43452148, 4.20305681, 2.85049756, 3.53903263,
        0.51891544, 1.00264071, 2.01810684, 0.        , 1.13980765,
        2.91413186, 1.34694483, 3.55600556, 0.96460567, 0.7720568 ,
        0.9714808 , 2.45988723, 1.98441869, 0.90405716, 2.65126194,
        2.8928674 , 1.41886973],
       [0.64166141, 1.02039206, 3.35646224, 3.39909146, 4.24710469,
        0.70456407, 1.54055037, 2.88905213, 1.13980765, 0.        ,
        3.33623585, 1.18456718, 4.3928947 , 1.11266574, 0.80224754,
        1.82223812, 2.8950295 , 1.99933589, 0.88678933, 2.54067707,
        3.76713062, 1.46983745],
       [2.8705364 , 2.62544334, 4.2403842 , 0.40219973, 3.14329577,
        3.02211956, 2.18058704, 2.08662491, 2.91413186, 3.33623585,
        0.        , 2.21571283, 2.87581314, 2.24149167, 3.0717928 ,
        2.26075542, 0.50143031, 1.82261404, 3.4222602 , 1.44816427,
        2.8818881 , 2.63971077],
       [0.96891338, 0.9306661 , 3.03221631, 2.33942345, 3.55026953,
        1.18197201, 0.90453801, 2.20513   , 1.34694483, 1.18456718,
        2.21571283, 0.        , 3.64288428, 0.46582008, 1.11846192,
        1.34044492, 1.77875376, 0.91201212, 1.63459069, 1.4377002 ,
        3.16631207, 1.0115158 ],
       [4.03997214, 3.4445976 , 5.77716087, 2.70949824, 0.79006816,
        3.98481703, 2.88293636, 1.56392154, 3.55600556, 4.3928947 ,
        2.87581314, 3.64288428, 0.        , 3.56869798, 3.67090606,
        2.62656448, 2.69733853, 3.11165994, 4.44443417, 3.82344699,
        0.79663971, 3.16665951],
       [0.66630734, 0.59466725, 3.47933654, 2.28716169, 3.54569181,
        0.84764872, 0.76820661, 2.0513037 , 0.96460567, 1.11266574,
        2.24149167, 0.46582008, 3.56869798, 0.        , 1.00160323,
        1.09229117, 1.80123296, 1.23604644, 1.30648913, 1.70555706,
        3.04901989, 1.16178367],
       [0.85370772, 0.60051186, 3.59289206, 3.09806061, 3.49319543,
        0.76171099, 0.96595801, 2.21325071, 0.7720568 , 0.80224754,
        3.0717928 , 1.11846192, 3.67090606, 1.00160323, 0.        ,
        1.18912089, 2.58594586, 1.68454335, 1.214794  , 2.54231114,
        3.01403299, 0.8823501 ],
       [1.42539767, 0.82523032, 4.19392258, 2.18229906, 2.6265492 ,
        1.35916245, 0.47341338, 1.08201067, 0.9714808 , 1.82223812,
        2.26075542, 1.34044492, 2.62656448, 1.09229117, 1.18912089,
        0.        , 1.78355684, 1.49392553, 1.83652016, 2.32895278,
        2.01898755, 1.13770288],
       [2.44441009, 2.15686663, 4.00181121, 0.63840368, 2.89012675,
        2.58372057, 1.68442573, 1.70980785, 2.45988723, 2.8950295 ,
        0.50143031, 1.77875376, 2.69733853, 1.80123296, 2.58594586,
        1.78355684, 0.        , 1.38751606, 3.01371083, 1.29327906,
        2.58527529, 2.14713324],
       [1.83270191, 1.56028205, 2.90178907, 2.02458061, 2.95236046,
        1.98939873, 1.09043124, 1.93104646, 1.98441869, 1.99933589,
        1.82261404, 0.91201212, 3.11165994, 1.23604644, 1.68454335,
        1.49392553, 1.38751606, 0.        , 2.49150093, 1.21258661,
        2.76970129, 1.01789843],
       [0.66626965, 1.09006272, 4.1783156 , 3.39116359, 4.43259035,
        0.53570799, 1.7498704 , 2.89148862, 0.90405716, 0.88678933,
        3.4222602 , 1.63459069, 4.44443417, 1.30648913, 1.214794  ,
        1.83652016, 3.01371083, 2.49150093, 0.        , 2.89830577,
        3.79422189, 2.01427645],
       [2.27586589, 2.26151045, 2.90280443, 1.76799544, 3.83275277,
        2.52283605, 1.98256158, 2.71203015, 2.65126194, 2.54067707,
        1.44816427, 1.4377002 , 3.82344699, 1.70555706, 2.54231114,
        2.32895278, 1.29327906, 1.21258661, 2.89830577, 0.        ,
        3.62942932, 2.13778824],
       [3.44124342, 2.82671717, 5.48243819, 2.71247363, 0.92289279,
        3.34917415, 2.32477018, 1.05246953, 2.8928674 , 3.76713062,
        2.8818881 , 3.16631207, 0.79663971, 3.04901989, 3.01403299,
        2.01898755, 2.58527529, 2.76970129, 3.79422189, 3.62942932,
        0.        , 2.60928543],
       [1.4694394 , 1.06683046, 3.20335262, 2.73103609, 2.89953955,
        1.49789511, 0.7680877 , 1.86764988, 1.41886973, 1.46983745,
        2.63971077, 1.0115158 , 3.16665951, 1.16178367, 0.8823501 ,
        1.13770288, 2.14713324, 1.01789843, 2.01427645, 2.13778824,
        2.60928543, 0.        ]])

In [36]:
#SE DETERMINA LA CANTIDAD DE K (CLÚSTERES) ÓPTIMA
import kmedoids

kmin = 2
kmax = 10
dm = kmedoids.dynmsc(distances, kmax, kmin, random_state=111)
print("Número óptimo de clústeres según el método de la Silueta:", dm.bestk)
print("Silueta medoide sobre el rango de K:", dm.losses)
print("Rango de K:", dm.rangek)

Número óptimo de clústeres según el método de la Silueta: 6
Silueta medoide sobre el rango de K: [0.66918737 0.67756029 0.71852862 0.70768387 0.73899642 0.61809346
 0.65213397 0.68768683 0.721986  ]
Rango de K: [ 2  3  4  5  6  7  8  9 10]

In [37]:
#MODELO DE CLUSTERIZACIÓN K-MEDOID
km = kmedoids.KMedoids(6, method = 'fasterpam', max_iter=100)
c = km.fit(distances)
print("La pérdida es:", c.inertia_)

labels_md = km.labels_
centroids_md = km.cluster_centers_
X_clustering['label_md'] = labels_md

# Cambiar el indice de los datos por una variable categorica "provincia"
X_clustering.index = df['province']
X_clustering.index
X_clustering

La pérdida es: 11.253983810137099

,z_school_dropout,z_illiteracy,z_doctors_per_cap,label_md
province,,,,
Buenos Aires,-0.853003,-1.013730,-0.039069,1
Catamarca,-0.687099,-0.455425,-0.263350,1
Córdoba,-0.612902,-0.240447,3.551749,0
Corrientes,1.913420,-0.223286,-0.267934,4
Chaco,0.764379,2.550462,-0.866760,5
Chubut,-1.013607,-0.917966,-0.266068,1
Entre Ríos,-0.253304,0.033471,-0.144510,3
Formosa,0.488917,0.861463,-0.977277,3
Jujuy,-0.893073,-0.567417,-0.629194,1
La Pampa,-1.354904,-0.923056,0.350293,1
La Rioja,1.896172,-0.206126,0.133529,4
Mendoza,-0.253304,-0.539058,0.555776,2
Misiones,1.256982,2.170688,-1.353917,5
Neuquén,-0.292828,-0.688061,0.116203,2
Río Negro,-1.172789,-0.223286,0.002791,1
Salta,-0.213779,0.126731,-0.606961,3
San Juan,1.408146,-0.095702,0.100821,4
San Luis,0.248892,0.177605,0.812602,2
Santa Cruz,-1.278853,-1.357553,-0.419007,1
Santa Fe,1.027546,-0.669358,1.195642,2
Santiago del Estero,0.539479,1.826804,-1.393514,5
Tucumán,-0.664488,0.373247,0.408154,2

In [38]:
#VISUALIZACIÓN DE LA CLUSTERIZACIÓN
import plotly.express as px
import plotly.io as pio
pio.renderers.default = 'browser'

In [39]:
fig = px.scatter_3d(X_clustering, x = "z_school_dropout", y = "z_illiteracy", z = "z_doctors_per_cap", color = 'label_md', hover_name = X_clustering.index)
fig.show()